---
title: "Notebooks"
---

This page contains a set of notebooks in Julia, R and Python for some of the data analyses presented in the book.

+-------------------------+------------------------------------------------+------------------------------------------------------------------------------+
| Chapter                 | Topic                                          | Language                                                                     |
+=========================+================================================+==============================================================================+
| Single-parameter models | Bernoulli model for spam data                  | [R](notebooks/SpamBern/SpamBernR.ipynb)\                                     |
|                         |                                                | [Julia/Pluto](notebooks/SpamBern/BernBeta.jl)                                |
+-------------------------+------------------------------------------------+------------------------------------------------------------------------------+
| Single-parameter models | Normal model for internet download speed data  | [R](notebooks/DownloadSpeedNormal/DownloadSpeedNormalR.ipynb)                |
+-------------------------+------------------------------------------------+------------------------------------------------------------------------------+
| Single-parameter models | Poisson for number of eBay bidders             | [R](notebooks/ebayPoissonOneParam/eBayPoissonR.ipynb)\                       |
|                         |                                                | [Python](notebooks/ebayPoissonOneParam/eBayPoissonPython.ipynb)              |
+-------------------------+------------------------------------------------+------------------------------------------------------------------------------+
| Multi-parameter models  | Multinomial model for survey data              | [R](notebooks/SurveyMultinomial/multinomial.Rmd)\                            |
|                         |                                                | [Julia/Pluto](notebooks/SurveyMultinomial/multinom.jl)                       |
+-------------------------+------------------------------------------------+------------------------------------------------------------------------------+
| Classification          | Logistic regression for spam data              | [R](notebooks/SpamLogisticReg/SpamLogisticReg.Rmd)                           |
+-------------------------+------------------------------------------------+------------------------------------------------------------------------------+
| Sequential inference    | Filtering and smoothing of the Nile river data | [Julia](notebooks/KalmanFilteringSmoothing/R_KalmanFilteringSmoothing.ipynb) |
+-------------------------+------------------------------------------------+------------------------------------------------------------------------------+
