---
title: "Modeling galaxy velocities with a Dirichlet process mixture model"
author: "Mattias Villani"
draft: true
format:
  html:
    fig-align: center
    toc: true
bibliography: ../notebook.bib
csl: ../apa.csl
---

## Introduction

The **galaxy velocity data**[^1] consists of the velocities of 82 galaxies (measured in 1000km/s, after transformation). The scientific question is whether or not the velocities of the galaxies cluster around a few values, which would indicate that the galaxies are part of a few superclusters[^2].

[^1]: Postman, M., Huchra, J. P. and Geller, M. J. (1986) Probes of large-scale structures in the Corona Borealis region. *Astronomical Journal* **92**, 1238–1247.

[^2]: [Roeder, K. (1990). *Density estimation with confidence sets exemplified by superclusters and voids in the galaxies*. Journal of the American Statistical Association, 85(411), 617-624](https://doi.org/10.1080/01621459.1990.10474918)

The analysis here first explores the **Dirichlet process** as a prior directly on the distribution (cdf) of the velocities before moving on to the more interesting **Dirichlet process mixture (DPM) model**. The DP mixture makes it possible to learn about the number of mixture components in the data, i.e. to explore the possibility of superclusters of galaxies.

```{julia}
#| code-fold: true
#| code-summary: "Code for loading packages and plot settings."
#| output: false
using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))
using CSV, HTTP, DataFrames, Plots, LaTeXStrings, Random
using Distributions, Measures, KernelDensity

colors = ["#6C8EBF", "#c0a34d", "#780000", "#007878", 
    "#b5c6df", "#eadaaa","#AE6666", "#4CA0A0","#bf9d6c"]
gr(grid = false, lw = 1, titlefontsize = 12)  
Random.seed!(123); # set the random seed for reproducibility
```

The data are available in the `galaxy` dataset in the `MASS` package in R. We inspect the data by plotting a histogram and a kernel density estimate using cross-validation to select the optimal bandwidth. At least three clusters are visible in the histogram, while the kernel density estimate suggest up to seven clusters.

```{julia}
#| code-fold: true
#| code-summary: "Show the code"
url = "https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv" * 
    "/MASS/galaxies.csv"
df = CSV.read(HTTP.get(url).body, DataFrame)
velocity = df.dat/1000
xlimits = [5,40]
xGrid = range(xlimits[1], xlimits[2], length = 1000)
n = length(velocity)
plt_data = histogram(velocity, xlim = xlimits, fillcolor=colors[6], linecolor = colors[2],
    normalize = true, label="histogram", lw = 0.5, xlabel="Velocity (km/s)", 
    ylabel="density", title="Histogram")
kde = kde_lscv(velocity)
plot!(plt_data, xGrid, pdf.(kde, xGrid), xlim = xlimits, color=colors[1], label="kde", 
    lw = 1.5, xlabel="Velocity (km/s)", ylabel="density", 
    title="Kernel density estimate", size = (400,300))
```

## Dirichlet process prior for the cdf

We first analyze the cumulative distribution function (cdf) of the velocities using a Dirichlet process prior.

#### Empirical cdf

The empirical cumulative distribution function (cdf) for the data can be computed by

```{julia}
function empirical_cdf(x, xlimits)
    xs = sort(x)
    ps = (1:length(xs)) ./ length(xs)
    xs = [xlimits[1];xs;xlimits[2]]
    ps = [0;ps;1]
    return xs, ps
end

xs, ps = empirical_cdf(velocity, xlimits)
plot(xs, ps, seriestype = :steppost, color = :black, label = "Empirical cdf", 
    size = (400,300))
```

When we later combine the empirical cdf with a Dirichlet process prior to form the posterior distribution it will be convenient to have proper Julia distribution object for the empirical cdf. We therefore approximate it with a mixture of normals with components with tiny ($10^{-15}$ ) variances, effectively making it a mixture of Dirac spikes at the data points with equal weights $1/n$. The plot belows shows that the approximation is virtually identical to the true empirical cdf.

```{julia}
Fₙ = MixtureModel([Normal(μ, 1.0e-15) for μ in velocity])
plot!(xGrid, cdf(Fₙ, xGrid), color = colors[2], label = "Normal mixture approx")
```

#### Prior distribution

Let $P$ denote the unknown distribution for the galaxy velocities. We use a Dirichlet process for $P$, denoted by $P \sim \mathrm{DP}(\alpha_0P_0)$. The $P_0$ is the so called **base measure** and is our best prior guess (prior expected value) of $P$. We take $P_0$ to be the $N(30,3^2)$ distribution. The scalar parameter $\alpha_0$ is the prior concentration or **prior precision**, which is inversely related to the variance around $P_0$. We start with low prior concentration $\alpha_0=1$ and later explore the effect of changing $\alpha_0$.

```{julia}
#| output: false
P₀ = Normal(20, 3)
α₀ = 1
```

At this stage we would like to simulate draws from the DP prior and plot the resulting distribution realizations, to get a feeling for the effect of $\alpha_0$. The so called stick-breaking representation of the Dirichlet process is a constructive characterization that makes it easy to simulate from a DP. The **stick-breaking representation** of the Dirichlet process is an infinite mixture of point masses $\delta_{\theta_k}$ at locations $\theta_k$ with weights $\omega_k$:

$$
\begin{align}
  P(\cdot) &= \sum_{k=1}^{\infty}\omega_{k}\delta_{\theta_{k}} \nonumber \\
  \omega_{k} &= V_{k}\prod_{\ell<k}(1-V_{\ell})  \nonumber \\
  V_{k} &\overset{\mathrm{iid}}{\sim}\mathrm{Beta}(1,\alpha_0) \nonumber \\
  \theta_{k} &\overset{\mathrm{iid}}{\sim}P_{0}
\end{align}
$$

The function below simulates from the Dirichlet process using the stick-breaking construction. The input $\epsilon$ is the remaining stick length when the simulation terminates.

```{julia}
#| output: false
function SimDirProcess(P₀, α₀, ϵ = 0.001)
    stickLeft = 1
    θ = Float64[]
    ω = Float64[]
    while stickLeft > ϵ
        θₖ = rand(P₀)
        Vₖ = rand(Beta(1, α₀))
        ωₖ = Vₖ*stickLeft
        stickLeft = stickLeft*(1-Vₖ) 
        push!(θ, θₖ) 
        push!(ω, ωₖ)
    end
    sortIdx = sortperm(θ)
    return θ[sortIdx], ω[sortIdx]
end
```

Here are a few draws from the prior for three different choices of $\alpha_0$.

```{julia}
nSim = 3
plts = [plot() for _ in 1:3]
for (j,α₀) in enumerate([1,10,100])
    for i = 1:nSim
        θ, ω = SimDirProcess(P₀, α₀)
        cdfdraw = [sum(ω[θ .< θᵢ]) for θᵢ in xGrid]
        plot!(plts[j], xGrid, cdfdraw, color = colors[i], label = "draw $i", 
            title = "Prior draws for "*L"\alpha_0 = %$(α₀)")
    end
end
plot(plts..., layout = (1,3), size = (800,300))
```

We can simulate a large number of draws and construct $95\%$ prior pointwise credible intervals for $P$, showing the variation in the prior. Let us first define a little helper function for computing quantiles for arrays:

```{julia}
quantile_multidim(A, p; dims, kwargs...) = mapslices(x->quantile(x, p; kwargs...), A; dims)
```

Here are the (pointwise) prior credible intervals for $\alpha_0=1$.

```{julia}
nSim = 10000
α₀ = 1
Priordraws = zeros(length(xGrid), nSim)
for i = 1:nSim
    θ, ω = SimDirProcess(P₀, α₀)
    Priordraws[:,i] = [sum(ω[θ .< θᵢ]) for θᵢ in xGrid]
end
priorQuantilesCDF = quantile_multidim(Priordraws, [0.025, 0.975], dims = 2)

plot(xGrid, cdf.(P₀, xGrid), label = L"P_0", c = colors[2], title = L"\alpha_0 = %$(α₀)", 
    legend = :topleft, size = (400,300))
plot!(xGrid, priorQuantilesCDF[:,1], lw = 0, fillrange = priorQuantilesCDF[:,2], 
    opacity = 0.2, c = colors[2], label = "Prior C.I.")
```

#### Posterior distribution

The posterior distribution for $P$ is also a Dirichlet process

$$
P \vert x_1,\ldots, x_n \sim \mathrm{DP}(\alpha_nP_n)
$$where the posterior precision is $\alpha_n = \alpha_0 + n$ and

$$
P_n = \frac{\alpha_0}{\alpha_n}P_0 + \frac{n}{\alpha_n}F_n
$$

is a mixture of the prior mean and the empirical cdf. We can use the `MixtureModel` object in Distributions.jl package elegantly:

```{julia}
αₙ = α₀ + n 
Pₙ = MixtureModel([P₀, Fₙ], [α₀/αₙ, n/αₙ]);
```

We can now plot the prior-to-posterior mapping. Here is the code and plot for $\alpha_0=100$.

```{julia}
nSim = 5000

# Prior
α₀ = 100
Priordraws = zeros(length(xGrid), nSim)
for i = 1:nSim
    θ, ω = SimDirProcess(P₀, α₀);
    Priordraws[:,i] = [sum(ω[θ .< θᵢ]) for θᵢ in xGrid]
end
priorQuantilesCDF = quantile_multidim(Priordraws, [0.025, 0.975], dims = 2)

# Posterior
αₙ = α₀ + n 
Pₙ = MixtureModel([P₀, Fₙ], [α₀/αₙ, n/αₙ]);
Postdraws = zeros(length(xGrid), nSim)
for i = 1:nSim
    θ, ω = SimDirProcess(Pₙ, αₙ);
    Postdraws[:,i] = [sum(ω[θ .< θᵢ]) for θᵢ in xGrid]
end
postQuantilesCDF = quantile_multidim(Postdraws, [0.025, 0.975], dims = 2)

plot(xGrid, cdf.(Fₙ, xGrid), label = L"F_n", c = colors[1], title = L"\alpha_0 = %$(α₀)", 
    legend = :topleft, size = (400,300))
plot!(xGrid, cdf.(P₀, xGrid), label = L"P_0", c = colors[2])
plot!(xGrid, cdf.(Pₙ, xGrid), label = L"P_n", c = colors[3])
plot!(xGrid, priorQuantilesCDF[:,1], lw = 0, fillrange = priorQuantilesCDF[:,2], 
    opacity = 0.2, c = colors[2], label = "Prior C.I.")
plot!(xGrid, cdf.(P₀, xGrid), label = "", c = colors[2])
plot!(xGrid, postQuantilesCDF[:,1], lw = 1, c = colors[3], label = "Post C.I.")
plot!(xGrid, postQuantilesCDF[:,2], lw = 1, c = colors[3], label = "")
plot!(xGrid, cdf.(Pₙ, xGrid), label = "", c = colors[3])
```

## Dirichlet process mixture

The posterior distribution for $P$ in the above analysis is almost surely discrete. This is an undesirable consequence of the Dirichlet process prior whenever $P$ is thought to be a continuous distribution.

However, the almost sure discreteness of the DP can be turned into a useful feature if the DP is used as mixing measure in a mixture model. A mixture model for the random variable $X$ is of the form

$$
p(x) = \int p(x \vert \mathbf{\theta})dP(\mathbf{\theta})
$$

where $p(x\vert\theta)$ is the kernel distribution with parameter vector $\mathbf{\theta}$ and $P(\mathbf{\theta})$ is the mixing distribution. The notation $dP(\mathbf{\theta})$ comes from measure theory and $P(\cdot)$ is a probability measure. This more general version of the integral makes it possible for $P(\cdot)$ be both a discrete and continuous probability distribution, or a mixture of the two types. There are three basic types of mixture distributions:

1.  **Continuous mixtures** where $P(\mathbf{\theta})$ is a continuous distribution with density $p(\theta)$ so we can write the more familiar integral $p(x) = \int p(x \vert \mathbf{\theta})p(\mathbf{\theta})d\mathbf{\theta}$. Example: the student $t$ density is a mixture of Gaussian kernels where the variance parameter of the kernel is mixed with respect to a scaled-inverse-chi-square distribution.

2.  **Finite discrete mixtures**\
    $$p(x) = \sum_{k=1}^K \omega_k \cdot N(x\vert \mu_k, \sigma_k^2),$$\
    where the kernel is again Gaussian, but the mixing distribution is a mixture of $K$ point masses for the mean and variance of the kernel. Since the mixing distribution $P(\cdot)$ is discrete here, the integral reduces to a sum.

3.  **Infinite discrete mixtures**\
    $$p(x) = \sum_{k=1}^\infty \omega_k \cdot N(x\vert \mu_k, \sigma_k^2),$$\
    where the most popular version is the Dirichlet Process Mixture (DPM) model, which is obtained when $P(\mathbf{\theta})$ is a *random distribution* following a Dirichlet process. The Dirichlet Process Mixture (DPM) model can be written\
    $$
    \begin{aligned}  
    x_i \vert \mathbf{\theta}_i &\overset{iid}{\sim} p(x_i \vert \mathbf{\theta}_i) \\  \mathbf{\theta}_i \vert P &\overset{iid}{\sim} P \nonumber \\  
    P &\sim \mathrm{DP}(\alpha_0 P_0)
    \end{aligned} 
    $$

Since realizations from the DP is almost surely discrete there will usually be several observations sharing the same parameter value $\mathbf{\theta}_j^{\star}$. In the case with a Gaussian kernel, the parameter vector is $\mathbf{\theta} =(\mu,\sigma^2)$ and the base measure $P_0$ is taken to be the conjugate prior:

$$
\begin{aligned}
\mu \vert \sigma^2 \sim N\bigg(\mu_0,\frac{\sigma^2}{\kappa_0}\bigg) \\
\sigma^2 \sim \mathrm{Inv}-\chi^2(\nu_0, \sigma_0^2)
\end{aligned} 
$$In the Gibbs sampler presented below, we will need to compute the posterior of $\mathbf{\theta} =(\mu,\sigma^2)$ for all the observations currently allocated to a mixture component. This little help function computes the posterior parameters $\mu_n,\kappa_n,\sigma_n^2$ and $\nu_n$ from a given data vector `x`:

```{julia}
#| output: false
function PostNormalModel(x, μ₀, σ²₀, κ₀, ν₀)
    if isempty(x) # no data, drawing from the prior
        return μ₀, σ²₀, κ₀, ν₀
    end
    x̄ = mean(x)
    n = length(x)
    κₙ = κ₀ + n
    w = n/(κ₀ + n)
    μₙ = w*x̄ + (1-w)*μ₀
    νₙ = ν₀ + n
    sumsqr = sum((x .- x̄).^2)
    σₙ² = (ν₀*σ²₀ + sumsqr  + (κ₀*n/κₙ)*(x̄-μ₀)^2)/νₙ
    return μₙ, σₙ², κₙ, νₙ
end
```

The Bayesian learning book uses the Scaled inverse Chi-square distribution, which is not available in Distributions.jl, but we can easily cook our own using the `InverseGamma` distribution in Distributions.jl:

```{julia}
#| output: false
ScaledInverseChiSq(ν,τ²) = InverseGamma(ν/2,ν*τ²/2)
```

The complete blocked Gibbs sampler for the DPM model with Gaussian components is given below. The sampler was developed in [@ishwaran2001gibbs]; see also [@villani_bayesbook]. The prior precision $\alpha_0$ can be fixed, or assigned a $\alpha_0 \sim \mathrm{Gamma}(g,h)$ prior and learned from the data. If `α₀ = nothing` then $\alpha_0$ is estimated.

```{julia}
#| output: false
function GibbsDPMixtureOfNormals(x, K, nIter, nBurn, P₀, α₀ = nothing, g = 1, h = 1)

n = length(x)
μ₀, σ²₀, κ₀, ν₀ = P₀

# Initial values
z = zeros(Int, n)  # mixture allocation z[i] ∈ {1,…,K}
ωpost = zeros(K)
if K == 1
    μ = [mean(x)]
else
    μ = collect(range(extrema(x)..., length = K))     
end    
σ² = (var(x)/K)*ones(K)
ω = (1/K)*ones(K)
V = zeros(K)       # storage for the stick-breaking 
if isnothing(α₀)
    estimate_α₀ = true
    α₀draws = zeros(nIter)
    α₀ = 1 # initial value
else
    estimate_α₀ = false
    α₀draws = nothing
end

# Storage
μdraws = zeros(nIter, K)
σ²draws = zeros(nIter, K)
ωdraws = zeros(nIter, K)
K_occupied = zeros(Int8, nIter) # n. of occupied components
for j = 1:(nBurn+nIter)

    # Update component allocations
    for i = 1:n
        ωpost = ω .* pdf.(Normal.(μ, sqrt.(σ²)), x[i]) 
        z[i] = rand(Categorical(ωpost / sum(ωpost)))
    end
    nInComps = [sum(z .== k) for k in 1:K]

    # Update component parameters
    for k = 1:K
        μₙ, σₙ², κₙ, νₙ = PostNormalModel(x[z .== k], μ₀, σ²₀, κ₀, ν₀)
        σ²[k] = rand(ScaledInverseChiSq(νₙ,σₙ²))
        μ[k] = rand(Normal(μₙ, sqrt(σ²[k]/κₙ)))
    end
    

    # Update component probabilities
    stickLength = 1
    for k = 1:(K-1)
        αpost = 1 + nInComps[k]
        βpost = α₀ + sum(nInComps[k+1:end])
        V[k] = rand(Beta(αpost, βpost))
        ω[k] = V[k] * stickLength
        stickLength = stickLength * (1 - V[k])
    end
    ω[K] = stickLength # Whatever is left

    # Update α₀. Scale parameterization for the Gamma
    if estimate_α₀
        α₀ = rand(Gamma(g + K + 1, 1/(h - sum(log.(1 .- V[1:K-1])))))
    end

    if j>nBurn
        μdraws[j-nBurn,:] = μ
        σ²draws[j-nBurn,:] = σ²
        ωdraws[j-nBurn,:] = ω
        K_occupied[j-nBurn] = sum(nInComps .> 0)
        if estimate_α₀ 
            α₀draws[j-nBurn] = α₀    
        end
    end

end

return μdraws, σ²draws, ωdraws, K_occupied, α₀draws

end
```

After setting the prior hyperparameters and upper bound of the number of mixtures components, we run the Gibbs sampler for `nBurn=1000` iterations as burn-in and then another `nIter = 10000` for posterior inference.

```{julia}
#| output: false
P₀ =  μ₀, σ²₀, κ₀, ν₀ = 20, 1^2, 0.1, 3
α₀ = 1
K = 30 # Upper bound on the number of components
nBurn = 1000
nIter = 10000
μdraws, σ²draws, ωdraws, K_occupied, α₀draws = GibbsDPMixtureOfNormals(velocity, K, 
    nIter, nBurn, P₀, α₀)
```

Plot the posterior mean of the fitted density for $\alpha_0=1$.

```{julia}
plt_post = deepcopy(plt_data)
plt_iter = 1:10:nIter
pdfDraws = zeros(length(plt_iter), length(xGrid))
for (count,i) in enumerate(plt_iter)
    pdfDraws[count,:] = pdf.(MixtureModel(
        [Normal(μdraws[i,k], sqrt(σ²draws[i,k])) for k in 1:K], ωdraws[i,:]), xGrid)
end
postMeanPDF = mean(pdfDraws, dims = 1)[:]
plot!(plt_post, xGrid, postMeanPDF, lw = 2, c = colors[3], 
    label = "post mean "*L"\alpha_0=%$(α₀)")
```

The posterior for the number of occupied mixture components has most of its mass on 5-10 components, with a mode at seven components:

```{julia}
K_max = maximum(K_occupied)
plt_bar = bar(0:K_max, [sum(K_occupied .== k) for k in 0:K_max],  
    fillcolor=colors[5], linecolor = colors[1],
    normalize = true, lw = 0.5, legend = false,
    xlabel="Number of components", ylabel="density", 
    title="Posterior for number of components", size = (400,300))
```

For $\alpha_0 = 10$ we get

```{julia}
α₀ = 10
μdraws, σ²draws, ωdraws, K_occupied, α₀draws = GibbsDPMixtureOfNormals(velocity, K, 
    nIter, nBurn, P₀, α₀)
plt_post = deepcopy(plt_data)
plt_iter = 1:10:nIter
pdfDraws = zeros(length(plt_iter), length(xGrid))
for (count,i) in enumerate(plt_iter)
    pdfDraws[count,:] = pdf.(MixtureModel(
        [Normal(μdraws[i,k], sqrt(σ²draws[i,k])) for k in 1:K], ωdraws[i,:]), xGrid)
end
postMeanPDF = mean(pdfDraws, dims = 1)[:]
plot!(plt_post, xGrid, postMeanPDF, lw = 2, c = colors[3], 
    label = "post mean "*L"\alpha_0=%$(α₀)")

K_max = maximum(K_occupied)
plt_bar = bar(0:K_max, [sum(K_occupied .== k) for k in 0:K_max],  
    fillcolor=colors[5], linecolor = colors[1], normalize = true, lw = 0.5, 
    legend = false, xlabel="Number of components", ylabel="density", 
    title="Posterior for number of components", size = (400,300))

plot(plt_post, plt_bar, layout = (1,2), size = (800,300), margin = 5mm)
```

For $\alpha_=100$

```{julia}
α₀ = 100
μdraws, σ²draws, ωdraws, K_occupied, α₀draws = GibbsDPMixtureOfNormals(velocity, K, 
    nIter, nBurn, P₀, α₀)
plt_post = deepcopy(plt_data)
plt_iter = 1:10:nIter
pdfDraws = zeros(length(plt_iter), length(xGrid))
for (count,i) in enumerate(plt_iter)
    pdfDraws[count,:] = pdf.(MixtureModel(
        [Normal(μdraws[i,k], sqrt(σ²draws[i,k])) for k in 1:K], ωdraws[i,:]), xGrid)
end
postMeanPDF = mean(pdfDraws, dims = 1)[:]
plot!(plt_post, xGrid, postMeanPDF, lw = 2, c = colors[3], 
    label = "post mean "*L"\alpha_0=%$(α₀)")

K_max = maximum(K_occupied)
plt_bar = bar(0:K_max, [sum(K_occupied .== k) for k in 0:K_max],  
    fillcolor=colors[5], linecolor = colors[1], normalize = true, lw = 0.5, 
    legend = false, xlabel="Number of components", ylabel="density", 
    title="Posterior for number of components", size = (400,300))

plot(plt_post, plt_bar, layout = (1,2), size = (800,300), margin = 5mm)
```

and finally when $\alpha_0$ is estimate using a Gamma(1,1) prior:

```{julia}
μdraws, σ²draws, ωdraws, K_occupied, α₀draws = GibbsDPMixtureOfNormals(velocity, K, 
    nIter, nBurn, P₀)
plt_post = deepcopy(plt_data)
plt_iter = 1:10:nIter
pdfDraws = zeros(length(plt_iter), length(xGrid))
for (count,i) in enumerate(plt_iter)
    pdfDraws[count,:] = pdf.(MixtureModel(
        [Normal(μdraws[i,k], sqrt(σ²draws[i,k])) for k in 1:K], ωdraws[i,:]), xGrid)
end
postMeanPDF = mean(pdfDraws, dims = 1)[:]
plot!(plt_post, xGrid, postMeanPDF, lw = 2, c = colors[3], 
    label = "post mean "*L"\alpha_0 \sim \mathrm{Gamma}(1,1)")

K_max = maximum(K_occupied)
plt_bar = bar(0:K_max, [sum(K_occupied .== k) for k in 0:K_max],  
    fillcolor=colors[5], linecolor = colors[1], normalize = true, lw = 0.5, 
    legend = false, xlabel="Number of components", ylabel="density", 
    title="Posterior for number of components", size = (400,300))

plot(plt_post, plt_bar, layout = (1,2), size = (800,300), margin = 5mm)
```

The posterior for $\alpha_0$ is

```{julia}
histogram(α₀draws, fillcolor=colors[7], linecolor = colors[3], opacity = 0.7, 
    size = (400,300), normalize = true, lw = 0.5, legend = false, xlabel = L"\alpha_0", 
    ylabel = "density")
```